---
kind: pipeline
type: docker
name: Test build

concurrency:
  limit: 1

steps:
    - name: Build
      image: sphinxdoc/sphinx
      commands:
        - pip3 install -r requirements.txt
        - make clean
        - make html
  
trigger:
    event: [ pull_request, push ] 